replicaCount: 2

image:
  repository: 422836431778.dkr.ecr.ap-south-2.amazonaws.com/demo-app
  tag: 1.0.0-668f392

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: demo-app-qa.example.com
      paths:
        - path: /
          pathType: Prefix

config:
  logLevel: info

environment: qa

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
