replicaCount: 1

image:
  repository: 483955930955.dkr.ecr.ap-south-2.amazonaws.com/demo-app
  tag: 1.0.0-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: demo-app.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

config:
  logLevel: info

secret:
  apiKey: changeme

probes:
  livenessPath: /health
  readinessPath: /health
